### ISSUE TITLE
Something different than `rake release`?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/guides#208]
Our open source protocol currently says to release using `rake release`:

https://github.com/thoughtbot/guides/tree/master/protocol/open-source

If I'm understanding things correctly, this results in a git tag, but not a GitHub release, being created like this:

https://github.com/thoughtbot/suspenders/releases/tag/v1.15.0

I think there needs to be a step after `rake release` where we write a nice message at https://github.com/thoughtbot/suspenders/releases/new?tag=v1.15.0 so it looks more like the nice one @mjankowski wrote at https://github.com/thoughtbot/suspenders/releases/tag/v1.14.0. Is that correct?

**Comment by jferris** [comment]
this discussion seems to have wrapped up, and there doesn't seem to be an immediate action item here. I'm going to close this, but feel free to comment if you have any further thoughts.
