### ISSUE TITLE
How we should break the long arguments line with no parentheses?

### ISSUE THREAD

**Issue by sikachu** [thoughtbot/guides#249]
So, given this line:

```ruby
attr_accessor :email, :name, :github_username, :password, :stripe_customer_id,
  :stripe_subscription_id, :stripe_token, :organization, :address1, :address2,
  :city, :state, :zip_code, :country
```

We've been doing this for so long, since we have these rules:

> * Don't vertically align tokens on consecutive lines.
> * Indent continued lines two spaces.

However, we have this rule:

> * If you break up an argument list, keep the arguments on their own lines and closing parenthesis on its own line.

... which after discussion with @gylaz it seems like we have to do this because of that rule:

```ruby
attr_accessor(
  :email,
  :name,
  :github_username,
  :password,
  :stripe_customer_id,
  :stripe_subscription_id,
  :stripe_token,
  :organization,
  :address1,
  :address2,
  :city,
  :state,
  :zip_code,
  :country
)
```

I feel like the intention of that rule _wasn't_ really intended for us to do that, as I remembered a lot of project that we have shitton of stuff in the same line and indent two spaces on the next line is just fine.

Do you think we should amend the rule so 1st code block form is acceptable? Or, was it that we stop doing it for so long and I just realized about it?

**Comment by jferris** [comment]
This conversation has gotten stale, so I'm going to close this. Feel free to open a pull request if you'd like to update the style guide.
