### ISSUE TITLE
Define subject when using Shoulda-Matchers' validate_uniqueness_of

### ISSUE THREAD

**Issue by c-lliope** [thoughtbot/guides#250]
Can we revisit #133 with respect to https://github.com/thoughtbot/shoulda-matchers/pull/567 ?

I just ran into the Non-NULL database column problem, where `validates_uniqueness_of` didn't know how to create a valid record.

Here's what the guides suggested my specs look like:

``` ruby
  describe "Validations" do
    it "validates uniqueness of email" do
      create(:registration)

      expect(Registration.new).to validate_uniqueness_of(:email)
    end

    it "validates uniqueness of mobile phone number" do
      create(:registration)

      expect(Registration.new).to validate_uniqueness_of(:mobile_phone_number)
    end

    it { is_expected.to validate_presence_of(:email) }
    it { is_expected.to validate_presence_of(:mobile_phone_number) }
  end
```

And here's what it looks like with an explicit subject:

``` ruby
  describe "Validations" do
    subject { build(:registration) }

    it { is_expected.to validate_presence_of(:email) }
    it { is_expected.to validate_presence_of(:mobile_phone_number) }
    it { is_expected.to validate_uniqueness_of(:email) }
    it { is_expected.to validate_uniqueness_of(:mobile_phone_number) }
  end
```

I would suggest that the second option is more readable and more manageable, with less duplication. Thoughts on allowing an explicit subject for use with shoulda-matchers?

**Comment by TorvaldsDB** [comment]
```ruby
require 'rails_helper'

RSpec.describe Score, type: :model do
  let(:score) { build(:score) }
  subject { described_class }

  it { is_expected.to validate_numericality_of(:score) }

  it 'belongs to staff' do
    assoc = subject.reflect_on_association(:staff)

    expect(assoc.macro).to eq :belongs_to
  end
end
```
This is my codes,  but I occurred the issues, looks like this: 
```ruby
» rspec spec/models/score_spec.rb                                                                                                                             [ruby-2.5.1][19:04:09]
F

Failures:

  1) Score should validate that :score looks like a number
     Failure/Error: it { is_expected.to validate_numericality_of(:score) }

     Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeDoesNotExistError:
       The matcher attempted to set :score on the Class to "abcd", but that
       attribute does not exist.
```
my `Score` looks like this:
```ruby
class Score < ApplicationRecord
  belongs_to :staff

  validates :score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end
```
why? and Thank you very much.

**Comment by jessieay** [comment]
@TorvaldsDB when you set `subject { described_class }` that is for the `Score` *class* , but you should always test validations on an *instance* of a class. So if you change that to `subject { described_class.new }` it should pass or give you a different error at least.

In Grayson's example above, he sets `subject { build(:registration) }` - this is shorthand for `subject { FactoryBot.build(:registration) }`, which is creating an instance of the `Registration` class.

We frequently use FactoryBot (https://github.com/thoughtbot/factory_bot) in test suits to easily create objects for tests. You might consider giving it a try.
