### ISSUE TITLE
Express style guides in code

### ISSUE THREAD

**Issue by mmwtsn** [thoughtbot/guides#261]
When applicable, it would be useful to have the style guides be accompanied by a linter recommendation and a config file for that linter. This would make it easier to enforce these recommendations programmatically as well as ease adoption for those interested.

Hound may soon take the place of these static code analysis tools but until additional languages are supported I think this is a good alternative for those that cannot use Hound for whatever reason.

I started translating the SCSS guidelines into an [SCSS-Lint](https://github.com/causes/scss-lint) config but was unsure where to add the new file. The [style/README.md](https://github.com/thoughtbot/guides/blob/master/style/README.md) file is already quite long. Mirroring the structure of "Protocol" makes sense to me. Each section could be broken out into a directory with a README, lint config and code sample:

```
style/
├── README.md
└── sass
    ├── README.md
    ├── sample.scss
    ├── .scss-lint.yml
```

Though this may be a moot point if the repository is being restructured at all for the move to GitHub Pages in #142.

Thoughts?

**Comment by jferris** [comment]
This is being discussed in Hound: https://github.com/thoughtbot/hound/issues/293
