### ISSUE TITLE
Don't pad code blocks with newlines when part of a test phase.

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/guides#274]
Regarding these two rules:
> Use empty lines around multi-line blocks.

From [formatting guidelines](https://github.com/thoughtbot/guides/tree/master/style#formatting)

> Separate setup, exercise, verification, and teardown phases with newlines.

From [testing guidelines](https://github.com/thoughtbot/guides/tree/master/style#testing).

I don't think it makes sense to mix them in tests.

The reason for the second guideline is to make it easy, at a glance, to distinguish the test phases (setup, execution, verification). Combine that with padding trivial blocks with newlines, and the benefit of the second guideline is greatly diminished.

Imagine a scenario where you have a test like the screenshot below. If we apply the squint/blur test to simulate at-a-glance identification of test phases, we can see that it's much harder to see the test phases in the second test; thus, unnecessary confusion!

![test phases](https://cloud.githubusercontent.com/assets/116327/5407067/76b1e62a-8173-11e4-8bbb-a34458ff59fd.png)

I understand that wrapping blocks with newlines can help with code esthetics. However, identifying a test phase at a glance is more important, IMO, than a subjective esthetic.

Does it make sense to clarify the rule of "Use empty lines around multi-line blocks."? On the other hand, maybe it's worth removing it unless there a practical reason to have that guideline?

**Comment by jferris** [comment]
I'm going to close this for now, as the discussion seems to have wrapped up, but feel free to reopen or submit a pull request if you think this warrants further action.
