### ISSUE TITLE
"Exceptions should be exceptional" broken link

### ISSUE THREAD

**Issue by etdev** [thoughtbot/guides#281]
Under [Best Practices > General](https://github.com/thoughtbot/guides/tree/master/best-practices), "Exceptions should be exceptional" links to http://www.readability.com/~/yichhgvu. 

This link redirects to http://pragmatictips.com/34, which is dead (and it appears has been for a while).

Here's a cached version: http://webcache.googleusercontent.com/search?q=cache:b9TMRPZjC_EJ:pragmatictips.com/34+&cd=2&hl=en&ct=clnk&gl=us.

I've mirrored the content [here](http://etdev.me/pragmatic/34/) and I can submit a PR replacing the link if you're interested.

**Comment by jferris** [comment]
Fixed in c95ba094b5.
