### ISSUE TITLE
Guidelines for animation

### ISSUE THREAD

**Issue by jlebensold** [thoughtbot/guides#307]
Hi there,

I really appreciate the guidelines that you've put together here and I'm wondering if you have any thoughts on how to organize keyframes and animation transitions in SASS. Should keyframe definitions exist inline, or be kept separately? Would you consider moving all `transition` properties into an animations file?

**Comment by jferris** [comment]
@thoughtbot/design any thoughts?

**Comment by joshuaogle** [comment]
I do create a separate animations file and keep them there. I think it's nice to keep the collection of animations (in a styleguide sense) in mind when building new sections or keeping an eye out for ways to simplify and refactor. I don't think we have any consistency on that among the design team though.

You could easily make an argument that keeping the animations with their elements is better, but I think it's good to stay modular.

**Comment by conchan** [comment]
I also keep all `keyframe`s in it's own separate file, for all the same reasons @joshuaogle mentioned.

For `transition`s, if I'm reusing them on multiple elements, I usually put those values in a variable and keep it within my variables file.

**Comment by jferris** [comment]
Thanks for the discussion. It seems like there isn't an action item here, so I'm going to close this. Feel free to open a pull request if we should change something in the guides.

**Comment by jlebensold** [comment]
@jferris Thanks everyone for sharing your thoughts – it was enriching and helped our own dev team :)
