### ISSUE TITLE
Guides on Gem Creation

### ISSUE THREAD

**Issue by CDainMiller** [thoughtbot/guides#314]
Hey guys,

Do you have any guides or thoughts around gem creation? 

For instance, if we look at your [fake_braintree](https://github.com/thoughtbot/fake_braintree) gem it's easy to see a bunch of best practices in use.  
- You have a contributing doc
- A great README that is very well structured
- A license file, etc. 

The gem structure itself (lib folder) is handled by bundler and the like, but even so, it'd still be awesome to have a suspenders-like utility to generate an open source gem repository fully set up in a way that you guys at Thoughtbot recommend, including all the docs and licenses you recommend etc.

I think a lot of intermediate rails developers (like myself) have a lot of ideas for gems, but the job of extracting things and getting set up to create an open source repo the correct way and to abstract the code is just too ambiguous. And this problem is magnified when the idea to create a gem usually strikes, which is usually in the middle of some large or complicated project, thus we just push off creating the gem to later. Anyway, what I'm getting at is I think such a utility could help out a little bit with that, if nothing else. :)

PS - If this already exists my apologies, but I couldn't find it.

**Comment by gabebw** [comment]
Hi! I wrote most of fake_braintree. Thank you for the compliment on the README.

The short answer is that I don't have a recommendation for something like suspenders for gems (but others might!). That's not a bad idea, though. There are a bunch of projects [on Ruby Toolbox](https://www.ruby-toolbox.com/categories/gem_creation) but they look unmaintained.

> The gem structure itself (lib folder) is handled by bundler and the like

As you might know, `bundle gem hi` will create a basic gem structure like this:

```
.
├── Gemfile
├── LICENSE.txt
├── README.md
├── Rakefile
├── hi.gemspec
└── lib
    ├── hi
    │   └── version.rb
    └── hi.rb
```

After running that, I run `rspec --init` in the base gem folder to get RSpec bootstrapped, copy in CONTRIBUTING.md from another thoughtbot project, and start TDDing my features.

It's worth noting, too, that a lot of our gems start out much (much) rougher than they are now. For example, fake_braintree started without a README and without any tests (!!): https://github.com/thoughtbot/fake_braintree/commit/8a222b5e8980bd6496e1b470890a3dfc25d81b62

**Comment by JuanitoFatas** [comment]
https://github.com/ruby-ore/ore This gem could be the starting point to customize your gem creation. I found this gem while reading [Postmodern - You don't have to use Bundler to create new RubyGems](http://postmodern.github.io/2012/05/20/you-dont-have-to-use-bundler-to-create-new-rubygems.html).

**Comment by mcmire** [comment]
I don't know if it's a good idea to write our own gem generator (there are about a billion out there already), but I think this would be good material for a blog post.

**Comment by CDainMiller** [comment]
Thanks for the feedback @gabebw @JuanitoFatas and @mcmire 

Also, that makes me feel better @gabebw that you started in a must less polished state. I suppose it's true that even thoughtbot employees are mere mortals and sometimes don't write tests! :8ball: hahah

**Comment by dideler** [comment]
+1 for a blog post - I think @gabebw got a good start going.

I've read blog posts & guides for creating a gem but often have to re-read them.
Most recently on my to-read list for gem building are
- https://blog.engineyard.com/2015/its-raining-gems
- http://www.justinweiss.com/blog/2015/02/17/a-guide-to-extracting-your-first-ruby-gem/

A concise post by thoughtbot would probably be *the* guide I refer to.

**Comment by bf4** [comment]
If anyone cares, I started one once, but haven't revisited it in a while https://github.com/howto-ruby/rubygems-style-guide

**Comment by gabebw** [comment]
Thanks for your feedback, everybody! I may just write that blog post.

While we're all here at the virtual table, are people more interested in how to write a ruby gem or how to extract code from existing projects and then stick it in a rubygem?

**Comment by bf4** [comment]
bundler itself uses a `Thor` to apply the [`new_gem` template](https://github.com/bundler/bundler/tree/master/lib/bundler/templates) just like rails templates do, which suspenders uses.  I've been meaning to generalize that code... right now I have something like the following... behaves similarly to a rails template. 

```ruby
# Usage:
# ruby __FILE__ NAME
# https://github.com/erikhuda/thor/wiki/Generators
# http://blog.tamouse.org/swaac/2014/03/08/playing-around-with-thor-generators/
# Inheriting from Thor::Group causes the defined methods to be executed in order
# rather than subcommands, when inheriting from 'Thor'
# e.g. https://github.com/bundler/bundler/blob/91633430cb/lib/bundler/cli.rb#L339-L352
#      https://github.com/bundler/bundler/blob/91633430cb/lib/bundler/cli/gem.rb#L18-L103
#      https://github.com/bundler/bundler/blog/91633430cb/lib/bundler/templates/newgem/Gemfile.tt
# class Bundler::CLI < Thor
#   class Gem
#     def initialize(options, gem_name, thor)
#      def run
#        opts = { :name => name, etc.
#        templates = { "Gemfile.tt" => "Gemfile", etc
#        templates.each do |src, dst|
#          thor.template("newgem/#{src}", target.join(dst), opts)
#        end
#   def gem(name)
#      Gem.new(options, name, self).run
#   end
#   def self.source_root
#     File.expand_path(File.join(File.dirname(__FILE__), 'templates'))
#   end
require 'thor'
require 'thor/group'
class Gemnerator < Thor::Group
  include Thor::Actions
add_runtime_options!
  class_option :verbose, default: false

  # expect one argument upon invocation,
  argument :name
  attr_reader :template_file

  def initialize(args = [], options = {}, config = {})
    @template_file = config.fetch(:template_file)
    super
    # Will apply template in File.join(destination_root, name)
    self.destination_root = config[:projects_root]
  end

  desc <<-FOO
Description:
  This generator makes or updates gems from a template
FOO

 def self.source_root
    File.expand_path("../templates/new_gem",__FILE__)
  end

  def app_name
    @app_name ||= snake_name
  end

  def apply_template
    apply(template_file, verbose: options[:verbose])
  end

  # munging on potential input from the user
  # 'Able & Louis: Go @@CRAXY@@' becomes
  # ["Able", "Louis", "Go", "CRAXY"]
  def name_components
    @_name_components ||= name.scan(/[[:alnum:]]+/)
  end

  # ["Able", "Louis", "Go", "CRAXY"] become
  # able_louis_go_craxy
  def snake_name
    @_snake_name ||= name_components.map(&:downcase).join("_")
  end
end
projects_root = ENV.fetch('PROJECT_DIR')
template = ENV.fetch("LOCATION")
fail "No template LOCATION value given. Please set LOCATION either as path to a file or a URL" if template.nil?
fail "Template #{template} does not exist" unless File.readable?(template)
template = File.expand_path(template) if template !~ %r{\A[A-Za-z][A-Za-z0-9+\-\.]*://}
args = ARGV
config = {
  projects_root: projects_root,
  template_file: template
}
Gemnerator.start(args, config)
```

**Comment by CDainMiller** [comment]
@gabebw Awesome mate!

To answer your question, for me, it's mainly a problem with the extraction of code. I also don't really know all the best practices around open sourcing gems so obviously there are multiple barriers to entry for someone in my position. BUT I think honestly extracting code from projects can be challenging, and is often I find a more likely scenario. I very rarely am just sitting around and think of a perfect idea for a gem - albeit that could be fairly common. 

I think that question is quite nuanced because the answers to both of the questions "How to write a gem" and "How to extract code from a project for a gem" could essentially be answered with the same article/screencast/video/etc, theoretically. So it is hard for me to find one of those to place more value in, than the other.

**Comment by dideler** [comment]
>  are people more interested in how to write a ruby gem or how to extract code from existing projects and then stick it in a rubygem?

Probably the latter, because I assume less guides exist for that compared to creating a gem from scratch.

**Comment by jferris** [comment]
Thanks for the discussion! I'm going to close this, as there doesn't seem to be anything we need to change in the guides to address this, but feel free to continue commenting.

**Comment by CDainMiller** [comment]
Awesome, thanks @jferris! 

Looking forward to a potential blog post on this topic when @gabebw isn't slammed with work! :) Thanks guys.
