### ISSUE TITLE
Regarding rebasing branches...

### ISSUE THREAD

**Issue by justin808** [thoughtbot/guides#340]
https://github.com/thoughtbot/guides/blob/master/protocol/git/README.md

```bash
git fetch origin
git rebase -i origin/master
```

Sometimes, small teams will work on a branch, but typically on different files within that branch.

Possibly the advice on rebasing should explain the pitfalls of doing the above rebase without coordinating with other branch users.

**Comment by justin808** [comment]
@mjankowski Do you have guidelines for multiple collabs on a branch?

**Comment by mjankowski** [comment]
Talk to each other.
