### ISSUE TITLE
Idea: Add a guide for designing and developing JSON APIs

### ISSUE THREAD

**Issue by malandrina** [thoughtbot/guides#364]
For context: This idea came out of the discussion on https://github.com/thoughtbot/robots.thoughtbot.com/pull/868.

We build a lot of JSON APIs at thoughtbot. We could be doing a better job of documenting the patterns, tooling, and specifications we've found work well for us.

What do folks think of adding a guide for designing and developing JSON APIs to `best-practices`?

**Comment by jferris** [comment]
I'm not opposed to having a JSON best practices guide, but it's hard to know if it would be helpful without actually seeing it. I think the next best step would be to put together a very rough draft and open a pull request.

**Comment by jessieay** [comment]
I think this is a great idea. 

iOS on Rails focuses more on the practical aspects of developing a JSON API w Rails, but there might be some stuff you can pull from that.

**Comment by malandrina** [comment]
Cool! PR opened: https://github.com/thoughtbot/guides/pull/365.

**Comment by malandrina** [comment]
Closing this issue now that https://github.com/thoughtbot/guides/pull/365 is merged.
