### ISSUE TITLE
Lonely Operator vs Null Object Pattern vs try! chains vs present? chains

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/guides#381]
Ruby 2.3.0 introduced the Lonely Operator:

https://bugs.ruby-lang.org/issues/11537

**Comment by mcmire** [comment]
We've talked about this before internally, and I don't think many of us are fans of this, as it encourages the use of `nil` to represent a meaningful value (when it truly shouldn't represent anything at all). It also makes violating the Law of Demeter really easy. We tend not to use `try` or `try!` for the same reason.

So I think it's one of those things that would be used sparingly, if absolutely necessary.

**Comment by toobulkeh** [comment]
So maybe a line in the guides suggesting a NullObject Pattern instead?

**Comment by mcmire** [comment]
That's what I would do. "Prefer the Null Object pattern over using `try`, `try!`, or the lonely operator (`&.`)." I'm curious what other people think, though.

**Comment by jferris** [comment]
It feels too early to write up a guideline on how to use this. Plenty of us have existing thoughts on `nil` and the Null Object pattern, but I'd suggest waiting until we have some Ruby 2.3 projects under our belts before jumping to conclusions.

**Comment by mike-burns** [comment]
I'm going to close this. We can revisit the topic with a pull request when we have more usage of this operator.

(Also, I can't think of a guideline for this that fits our guides; our guides are things we agree on, but not a list of decision trees on when to use language features.)
