### ISSUE TITLE
Typo in Playbook

### ISSUE THREAD

**Issue by jlebensold** [thoughtbot/guides#418]
Under Test and Learn:
The most likely outcome is that we'll want to run a follow-on sprint starting at Diverge or Converge and test again with **a** new users.

Should read
For a new product, it's unlikely that any team will nail it their first sprint. The most likely outcome is that we'll want to run a follow-on sprint starting at Diverge or Converge and test again with new users.

**Comment by tute** [comment]
This was fixed in the playbook, and next release will contain your suggestion. Thank you!
