### ISSUE TITLE
Rubocop TrailingComma Style

### ISSUE THREAD

**Issue by ivobenedito** [thoughtbot/guides#421]
Hi,

The [.rubocop.yml](https://github.com/thoughtbot/guides/blob/master/style/ruby/.rubocop.yml) file needs to be updated. 

The **Style/TrailingComma** cop is obsolete.
```shell
Error: The `Style/TrailingComma` cop no longer exists. 
Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
```

Same happens with **Rails/DefaultScope**.
```shell
Error: The `Rails/DefaultScope` cop no longer exists.
```

**Comment by jferris** [comment]
Thanks for pointing this out. I opened a pull request to address this.
