### ISSUE TITLE
Swift: Where should "let" go in a switch statement binding a local variable?

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/guides#429]
Just leaving this here for now as context: https://github.com/unitio-org/care-ios/pull/52/files/ed4c91728187cfae35f9b78cfdc03fb9e0032619#r68774101

I plan to return here to summarise the discussion and potentially open a PR.

**Comment by tonyd256** [comment]
Can't see that link for reasons already discussed BUT I usually like to have it outside the case so I only have to type it once for when the case has many variables. I know this can make the style seem inconsistent if other cases don't have a let ... and this also breaks the auto-complete but I'm cool with them being inside too if that's the project style.

**Comment by sharplet** [comment]
I actually switch to the outer `let` in exactly that case. So I suppose my current style could be summarised like so:

- Prefer a `let` closer to the variable name so that cases are consistently left-aligned
- If there are multiple variables being bound, switch to a single `case let` for clarity in the rest of the pattern

**Comment by tonyd256** [comment]
I've actually gone back and forth myself. I'm not sure I care so much for a hard rule here as long as people are consistent. Also, mostly upset that we even have to use `let`.

**Comment by jamescmartinez** [comment]
The original link is dead.

`let` me close this.

... sorry, that was *bad*.
