### ISSUE TITLE
Document iOS release process?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/guides#442]
Should the [iOS protocol](https://github.com/thoughtbot/guides/tree/master/protocol/ios) have something similar as the [Rails protocol](https://github.com/thoughtbot/guides/tree/master/protocol/rails#deploy)?

**Comment by sharplet** [comment]
I've recently done some work scripting as much as possible of the iOS deployment process on my projects. I'm pretty happy with the workflow at this point—after the initial setup, deploying a new build to TestFlight is a single command: `bin/release --new-build`. After a build passes app review and ships to the store, a new version can be deployed with `bin/release --new-version`. Here's the script: https://github.com/thoughtbot/listen-up-ios/blob/master/bin/release.

I mean to write up a blog post describing all the pieces soon.

The deployment part, while historically quite an involved process, doesn't cover everything that the Rails protocol does. But I'd be interested in working on fleshing that out after I've had a go writing up the deployment blog post.

ping @thoughtbot/ios

**Comment by croaky** [comment]
Closing for cleanliness.
