### ISSUE TITLE
Can I translate some essays in Chinese?

### ISSUE THREAD

**Issue by HaitianLiu** [thoughtbot/guides#443]
Hey, I've learn a lot in these amazing guides, and I plan to translate some best-favourite essays and share them.
Do I need to do it under permission?
Thank you.

**Comment by iwz** [comment]
These guides are licensed under the Creative Commons license: https://creativecommons.org/licenses/by/3.0/

This license states:

> You are free to:
> 
> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material
> for any purpose, even commercially.
> The licensor cannot revoke these freedoms as long as you follow the license terms.
> 
> Under the following terms:
> 
>  Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> 
> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

So, no, you do not need permission, as long as you abide by this license.
