### ISSUE TITLE
How do I: set up Hound analysis for a new project?

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/guides#444]
Not sure whether this belongs in guides or in something more internal:

1. Do the HoundCI dance (document those steps -- perhaps with screenshots!)
2. Use a styleguide from the guides repo, e.g. https://github.com/thoughtbot/guides/blob/master/style/ruby/.rubocop.yml

**Comment by mike-burns** [comment]
Further discussion here: https://thoughtbot.slack.com/archives/ruby/p1472148457001485

**Comment by jcmorrow** [comment]
Does this meet those needs? https://github.com/thoughtbot/handbook/pull/477

**Comment by jcmorrow** [comment]
I guess we should also add a bit about how to get the thoughtbot configuration if you aren't on a thoughtbot org repo, as only those are opted into our defaults now.

**Comment by mike-burns** [comment]
Nice! Thanks for that PR link. It meets half of the needs (in fact, it meets needs that I didn't realize I had until now), but it misses the configuration aspect.
