### ISSUE TITLE
Broken Link in Best Bractices

### ISSUE THREAD

**Issue by genericlady** [thoughtbot/guides#452]
https://github.com/thoughtbot/guides/tree/master/best-practices

Broken link for keeping it simple

https://www.readability.com/~/ko2aqda2

**Comment by tysongach** [comment]
Blame takes me back to this commit, which doesn’t do much to track down the original intent: https://github.com/thoughtbot/guides/commit/04b6e2ea8597ae46b24247b96da9b04645478fa0

**Comment by WaKeMaTTa** [comment]
readability is dead.

**Comment by tysongach** [comment]
https://github.com/thoughtbot/guides/pull/454

**Comment by tysongach** [comment]
This was fixed in https://github.com/thoughtbot/guides/commit/752db69a69a9dbaae1d80355641f1d0fe6bb5f10.
