### ISSUE TITLE
How should html element be selected for javascript use? 

### ISSUE THREAD

**Issue by AndreiMotinga** [thoughtbot/guides#462]
`<div id="select-me"></div>`
or 
`<div class="js-select-me"></div>`
or something else?

**Comment by derekprior** [comment]
I prefer to decorate elements with data attributes and have selectors target those data attributes. I've also done the `js-` thing before as well and that tends to work fine too.

Using an `id` breaks down as soon as you want two of these things on the page.

**Comment by AndreiMotinga** [comment]
I noticed `js-` approach is used in Refills. 
It works fine and I like it, but my understanding is, classes weren't meant for js, but for styles, right?

At the same time `$(".js-foo")` is nicer than `$("[data-id='foo']")`. Hence my question.
Is there a guideline for it? Should there be one?

**Comment by drapergeek** [comment]
I agree with Derek, I have a preference for data attributes where possible. I only use `.js-` in the case of a JS plugin that only allows classes as a lookup or some other strange reason.

I think a guideline for preferring data attributes for JS interactions would be great.

**Comment by AndreiMotinga** [comment]
Quick google search suggests that selecting elements with data attributes is significantly slower, especially with IE, and that this fact can't be ignored. I find this question pretty interesting.

**Comment by derekprior** [comment]
When writing simple jQuery-based behaviors and the like, I've never reached the point where selector performance was a constraining factor. I'm not saying it doesn't happen and all apps should evaluate this for themselves, but I haven't seen it.

**Comment by AndreiMotinga** [comment]
@derekprior I agree. I understand it would matter for a project like Refills.

**Comment by gylaz** [comment]
I've been using the `role` HTML attribute (similar to `data-role`). It communicates DOM-wide what the purpose of the element is.

**Comment by derekprior** [comment]
I believe those have a strict subset of technically allowed values: http://w3c.github.io/html/dom.html#allowed-aria-roles-states-and-properties

**Comment by gylaz** [comment]
> I believe those have a strict set of technically allowed values: http://w3c.github.io/html/dom.html#allowed-aria-roles-states-and-properties

Good to know! `data-` attribute is a better fit then.

**Comment by mike-burns** [comment]
> classes weren't meant for js, but for styles, right?

That's not my memory of history. I remember it as: `class` was introduced into HTML and, at the same time, CSS made use of them. I still live in a fantasy world where none of HTML has anything to do with CSS or JS and everything to do with semantics.

---

Do we need to decide on something here? Isn't this a case of "use `id` or `data-` or `class`, as appropriate"?

**Comment by wardpenney** [comment]
I just would like for styling to be de-coupled from meaning. If that is `[data-*]` or `.js-*` I could go either way. Sometimes I need to redesign stuff, and I would like to know declaratively what is meaningfully important so I can preserve it. 

I think in a dream world, `aria` roles would handle all the meaningful state changes, and the designer should have the freedom to respond.  CC @LloydBennett

**Comment by tysongach** [comment]
Any update here? There’s seems to be a consensus on:

- `id`s are not a great use for this
- Data attributes are preferred
- Classes can be used if needed, but they should not be tied to classes used for styling and it's probably a good idea to use some sort of prefix, like `js-`

Should we add these thoughts to the guides?

**Comment by AndreiMotinga** [comment]
> Should we add these thoughts to the guides?

I've found that a lot of people respect your way of doing things. So yeah, you should
