### ISSUE TITLE
Link to readability.com "dead"

### ISSUE THREAD

**Issue by fwolfst** [thoughtbot/guides#463]
The link to "keep the code simple" in
https://github.com/thoughtbot/guides/tree/master/best-practices
is "dead" (proprietary service shut down, yay Freemium). No idea how to get the links back.

**Comment by iwz** [comment]
Thanks for the report. This is a dupe of https://github.com/thoughtbot/guides/pull/454, closing

**Comment by fwolfst** [comment]
Sorry, checked other issues but apparently overlooked it?!
