### ISSUE TITLE
Reprinting the Code Review Guidelines

### ISSUE THREAD

**Issue by ascott1** [thoughtbot/guides#485]
Hi thoughtbot friends,

I'm working on a series of free books for O'Reilly on the Ethical Web Development (more info at [ethicalweb.org](https://ethicalweb.org/)). The last title in the series is called _Building Web Apps Together_ and in my initial draft I highly recommend thoughtbot's [code review guide](https://github.com/thoughtbot/guides/blob/master/code-review/README.md) and re-print an adapted version of the guide with credit along and a link to this repo. I know it is licensed under a Creative Commons Attribution License, but I wanted to give you a heads up. As much as I'd love to print the full guide in the book, I'd be happy to simply link to it if you'd prefer.

Thanks!

**Comment by ascott1** [comment]
Hi all,

I've gone ahead and included a modified version of the standards in the book, in compliance with the license (attribution and a link back to the standards). You can see a draft of it in context in the first draft: https://github.com/ascott1/ethical-web-dev/blob/master/building-web-apps-together/02-code-quality.md#code-reviews

I'm going to close this issue, but please let me know if you'd prefer that I include just a link. Thanks for writing such a helpful guide - I'm excited to share it!

**Comment by JoelQ** [comment]
@ascott1 Thanks for reaching out to us. We're glad you find our review guidelines helpful. Copying the guidelines with attribution + link (as you currently do in your draft) is 👍 👍 by us. Good luck with your book!

**Comment by ascott1** [comment]
Thanks @JoelQ!
