### ISSUE TITLE
Options to avoid testing private methods used in callbacks

### ISSUE THREAD

**Issue by rwehresmann** [thoughtbot/guides#489]
Currently I'm using [shoulda-callback-matchers](https://github.com/jdliss/shoulda-callback-matchers) to test if the right callbacks will be called in the right moments. However, I need to test the callback action itself. Normally I have the following:

```ruby
class MyModel < ApplicationRecord

before_create :set_correct

private

def set_correct
  ...
end
``` 

In this case I need to test my private method `set_correct` to check if the callback will do wath I want. That goes against the recomendadion of "don't test private methods".

I have a better option here or in this specific scenario it's ok test a private method?

**Comment by gylaz** [comment]
Instead of calling `set_correct` directly in your test, you can test the desired behavior by calling save on a new record.

**Comment by croaky** [comment]
See the describe create in https://github.com/houndci/hound/blob/master/spec/models/user_spec.rb and the associated callback in its User model as an example

**Comment by rwehresmann** [comment]
Understood! Thanks for the example @croaky
