### ISSUE TITLE
YouTube Video Unavailable 

### ISSUE THREAD

**Issue by pmacMaps** [thoughtbot/guides#548]
The [YouTube Video](https://www.youtube.com/watch?v=f84LymEs67Y) on [Phase 1: Understand](https://thoughtbot.com/playbook/product-design-sprint/phase-1-understand) is unavailable.

![Capture](https://user-images.githubusercontent.com/12861454/56970419-13bb6e00-6b35-11e9-8b76-d67f3d8b23fc.PNG)

**Comment by croaky** [comment]
I believe that was originally a Clayton Christensen video on JBTD. Something like https://www.youtube.com/watch?v=QEFAHIulWw4

**Comment by sarahcassidy-tb** [comment]
@kylefiedler which repo does the PDS guide live in?

**Comment by kylefiedler** [comment]
This seems like it's in the playbook not the PDS guide

**Comment by tysongach** [comment]
Yes, this content is in the Playbook, and can be found here (private repo): https://github.com/thoughtbot/thoughtbot.com/blob/master/app/playbook/product-design-sprint/phase-1-understand.md

**Comment by tysongach** [comment]
The fix for this is now live: https://thoughtbot.com/playbook/product-design-sprint/phase-1-understand

Thanks for reporting, @pmacMaps!
