### ISSUE TITLE
Should we delete empty (seemingly duplicate) graphql guide?

### ISSUE THREAD

**Issue by germsvel** [thoughtbot/guides#574]
We seem to have two GraphQL READMEs in the guides. 

* https://github.com/thoughtbot/guides/blob/master/graphql/README.md, and 

* https://github.com/thoughtbot/guides/blob/master/graphql/rails/README.md

The second one seems to be scoped to Rails, but it is also empty. I imagine we don't need two of them yet. Maybe one day we will if there's enough Rails-specific stuff. But for now, my guess is that we should probably delete the empty one. 

It seem @lancejjohnson created the Rails one and contributed to the non-Rails one. So Lance maybe you're particularly suited to know whether deleting one is a good idea?

**Comment by whyderrick** [comment]
I'd vote yes, if only because the Rails guide is empty and has been for 5 months. It feels like keeping unused code around to me.
