### ISSUE TITLE
Update Backbone guide?

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/guides#583]
Our [Backbone guide](https://github.com/thoughtbot/guides/tree/master/style/backbone) has never been updated since it was added in 2014. According to Hub, only [4 projects have been tagged with Backbone](https://hub.thoughtbot.com/skills/backbone/projects) (private link to thoughtbot team members). The [sample file](https://github.com/thoughtbot/guides/blob/master/style/backbone/sample.coffee) in `style/backbone` is written in CoffeeScript, which [we no longer encourage the use of](https://github.com/thoughtbot/guides/commit/86d22bb53de629dd81a604481922d8558f0f91c4).

Should we update this guide? Should it be removed if it’s no longer providing value? Something else?

**Comment by nickcharlton** [comment]
I think we should remove it; I've not seen Backbone on client projects in at least the past four years and those still using it I'd expect to have their own guides.

**Comment by JoelQ** [comment]
Backbone is no longer part of our stack. We don't do any projects with it, and it's been superseded by a new generation of JS frameworks. I think we should remove the guide.
