### ISSUE TITLE
Update Ember guide?

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/guides#584]
Our [Ember guide](https://github.com/thoughtbot/guides/blob/master/style/ember/README.md) has not been updated since 2015. According to Hub, there [appears to be some opposition to it](https://hub.thoughtbot.com/skills/ember/abilities) (private link to thoughtbot team members).

Should we update this guide? Should it be removed if it’s no longer providing value? Something else?

**Comment by mike-burns** [comment]
Same reasoning as in #583 : let's kill this guide off. We're not starting any new projects in Ember, and existing projects will come with their own guide.
