### ISSUE TITLE
Document Go Best Practices

### ISSUE THREAD

**Issue by ghostsquad** [thoughtbot/guides#604]

**Comment by jferris** [comment]
We don't currently use Go as part of our usual stack, so we don't have the experience or motivation to drive best practices in Go. I'm going to close this issue, as it's not something we're planning to work on, but feel free to comment if you have any further questions or thoughts.

**Comment by ghostsquad** [comment]
thanks for the thoughtful response! I'll keep looking for this kind of thing, and if I can't find it, I guess I can try to create it!
