### ISSUE TITLE
Our testing guides are ruby/rails-centric

### ISSUE THREAD

**Issue by WilHall** [thoughtbot/guides#611]
We have a guide on [testing best-practices](https://github.com/thoughtbot/guides/tree/master/best-practices#testing) and [testing style](https://github.com/thoughtbot/guides/tree/master/style/testing), but both contain guidelines specific to ruby/rails.

I noticed this in #603 when adding a [style guide for jest](https://github.com/thoughtbot/guides/pull/603/files#diff-6506acf0845c90847fba11ea15ff40de).

Some of the existing guidelines apply to testing across the board, and could live in a general guide on testing. For guidelines which might be language or framework specific (ruby vs. javascript, rspec vs. jest), where should those live?

Some thoughts on possible solutions:
1.  Promote our general testing guidelines to a top-level folder in this repository, and place language and framework specific guides (e.g. `testing-rspec`, `testing-jest`) into either `best-practices/` or `style/`
1. Add a section for each language/framework to the existing testing guides, and move the non-general guidelines into those sections
1. Only have specific guides -  rename the existing `testing` guide to be specific (`testing-rspec`? `testing-rails`?) and create new `testing-X` guides for other languages and frameworks

**Comment by JoelQ** [comment]
I like the idea of a high-level, framework-agnostic testing guide

**Comment by edwardloveall** [comment]
Agreed! Framework-agnostic guides in general are important to me. Another way to do it would be to make a `testing` directory which has a `README.md` with general guidelines and `rspec.md` and `jest.md` inside of it. The `README.md` could point to the other guides in the folder.
