### ISSUE TITLE
Data guide should use description lists

### ISSUE THREAD

**Issue by WilHall** [thoughtbot/guides#619]
The [data guide](https://github.com/thoughtbot/guides/blob/master/data/README.md) has a section of definitions as markdown.

The content would be more accessible and visually appealing if it used [definition lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) for outlining the terms.

**Comment by ej-mitchell** [comment]
Do you want to preserve the markdown version as well as have a version that uses HTML? AFAIK, HTML doesn't render in GitHub, but I did find [this](https://github.com/htmlpreview/htmlpreview.github.com). Were you imagining something like this being used in lieu of a markdown file?

**Comment by WilHall** [comment]
I think most HTML should render in GH-flavored markdown.

For example, here is a description list:

<dl>
    <dt>Beast of Bodmin</dt>
    <dd>A large feline inhabiting Bodmin Moor.</dd>
    <dt>Morgawr</dt>
    <dd>A sea serpent.</dd>
    <dt>Owlman</dt>
    <dd>A giant owl-like creature.</dd>
</dl>

Source:
```
<dl>
    <dt>Beast of Bodmin</dt>
    <dd>A large feline inhabiting Bodmin Moor.</dd>

    <dt>Morgawr</dt>
    <dd>A sea serpent.</dd>

    <dt>Owlman</dt>
    <dd>A giant owl-like creature.</dd>
</dl>
```

**Comment by ej-mitchell** [comment]
Oh nice. TIL. Thanks :)

**Comment by ej-mitchell** [comment]
Done :)
