### ISSUE TITLE
rebase workflow link missing from Git guide

### ISSUE THREAD

**Issue by jaredrapid** [thoughtbot/guides#631]
The link for [rebase workflow] is missing from the Git guide: https://github.com/thoughtbot/guides/blob/main/git/README.md

There are [various](https://docs.github.com/en/free-pro-team@latest/github/using-git/about-git-rebase) [guides](https://git-rebase.io/) out there but not sure if you had a particular one in mind.

**Comment by mike-burns** [comment]
Thanks for catching that. It should link to https://github.com/thoughtbot/guides/blob/main/git/README.md#merge .

---

I tracked down what happened. Originally we had a [git "style"] and a [git "protocol"] guide. In #615 we merged them. During this merge we lost the link.

[git "style"]: https://github.com/thoughtbot/guides/blob/4240c34185e8a9a31f5f735808516b52caa5c05e/style/git/README.md
[git "protocol"]: https://github.com/thoughtbot/guides/tree/4240c34185e8a9a31f5f735808516b52caa5c05e/protocol/git
