### ISSUE TITLE
A11y template

### ISSUE THREAD

**Issue by umaar** [thoughtbot/guides#675]
On: https://github.com/thoughtbot/guides/tree/main/accessibility it says

> Create a copy of the [Accessibility Audit Template](https://docs.google.com/spreadsheets/d/1Ys-0U5BY-Ct_phy7gk9XJmn4nBTMFTh08aTQ6U1kB_4/edit?usp=sharing) spreadsheet in Google Drive

That template link says "Sorry, the file that you've requested has been deleted."

**Comment by dorianmariefr** [comment]
I can't find the file in our drive, maybe it's this one: https://www.fsb.org.uk/resources-page/accessibility-audit-template.html what do you think?

**Comment by umaar** [comment]
Cool

**Comment by umaar** [comment]
Thanks!
